
-- Declaring variables for user IDs
DECLARE @LoganId NVARCHAR(100);
DECLARE @JulianaId NVARCHAR(100);

-- Setting the user IDs based on the user names
SET @LoganId = 'c70d18f6-3ef4-4141-86a2-216cf0749cc6';
SET @JulianaId = 'e3d33315-485d-4f1f-bc6f-1c2dc77f6704';

-- Inserting users into the User table
INSERT INTO [User] ([Id], [FirstName], [LastName]) VALUES (@LoganId, 'Logan', 'Farci');
INSERT INTO [User] ([Id], [FirstName], [LastName]) VALUES (@JulianaId, 'Juliana Marcela', 'Aguirre Cardona');


INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Omelette', @LoganId, 'A delicious omelette recipe invented by my grandma.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pancakes', @LoganId, 'A delicious pancake recipe invented by my grandma.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Bread', @LoganId, 'A delicious bread recipe invented by my grandma.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Spaghetti Carbonara', @LoganId, 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Margherita Pizza', @LoganId, 'A simple and delicious pizza topped with tomatoes, mozzarella, and basil.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tiramisu', @LoganId, 'A famous Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tacos', @LoganId, 'Authentic Mexican street tacos with flavorful fillings and toppings.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Enchiladas', @LoganId, 'Traditional Mexican dish with tortillas filled with meat, cheese, and sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Guacamole', @LoganId, 'Classic Mexican dip made with mashed avocados, lime juice, and seasonings.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chiles Rellenos', @LoganId, 'Stuffed Mexican peppers with a savory filling and topped with sauce and cheese.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Mole', @LoganId, 'Rich and flavorful Mexican sauce made with chocolate, spices, and chili peppers.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Sushi', @LoganId, 'Traditional Japanese dish made with vinegared rice and various toppings.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pad Thai', @LoganId, 'Popular Thai stir-fried noodle dish with shrimp, tofu, and peanuts.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Moussaka', @LoganId, 'Greek casserole dish with layers of eggplant, ground meat, and béchamel sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Paella', @LoganId, 'Spanish rice dish with saffron, seafood, and various meats.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Kimchi', @LoganId, 'Traditional Korean side dish made with fermented vegetables.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tacos al Pastor', @LoganId, 'Mexican street tacos with marinated pork and pineapple.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicken Tikka Masala', @LoganId, 'Indian curry dish with grilled chicken in a spiced tomato sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Peking Duck', @LoganId, 'Chinese dish of roasted duck served with pancakes and hoisin sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Goulash', @LoganId, 'Hungarian stew made with meat, vegetables, and paprika.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tiramisu', @LoganId, 'Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Baklava', @LoganId, 'Sweet pastry made with layers of phyllo dough, nuts, and honey syrup.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Ceviche', @LoganId, 'Latin American dish of raw fish marinated in citrus juice and spices.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Poutine', @LoganId, 'Canadian dish of fries topped with cheese curds and gravy.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Maple Syrup', @LoganId, 'Canadian syrup made from the sap of sugar maple trees.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('BeaverTails', @LoganId, 'Canadian pastry shaped like a beaver tail and topped with various sweet toppings.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Nanaimo Bars', @LoganId, 'Canadian dessert bars with layers of crumbly base, custard-flavored icing, and chocolate topping.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Poutine', @LoganId, 'Canadian dish of fries topped with cheese curds and gravy.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Butter Tart', @LoganId, 'Canadian pastry filled with a sweet mixture of butter, sugar, and eggs.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tourtière', @LoganId, 'Canadian meat pie made with ground pork and spices.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Nanaimo Bars', @LoganId, 'Canadian dessert bars with layers of crumbly base, custard-flavored icing, and chocolate topping.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('BeaverTails', @LoganId, 'Canadian pastry shaped like a beaver tail and topped with various sweet toppings.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Butter Tart', @LoganId, 'Canadian pastry filled with a sweet mixture of butter, sugar, and eggs.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Mussels with Fries', @LoganId, 'Belgian dish of steamed mussels served with crispy fries.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Carbonade Flamande', @LoganId, 'Traditional Belgian beef stew cooked in beer with onions and spices.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Liege Waffles', @LoganId, 'Belgian waffles made with a yeast-based dough and pearl sugar.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Waterzooi', @LoganId, 'Creamy Belgian stew made with chicken or fish, vegetables, and herbs.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Speculoos', @LoganId, 'Belgian spiced shortcrust biscuit often enjoyed with coffee or tea.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Stoemp', @LoganId, 'Belgian dish of mashed potatoes mixed with vegetables like carrots, leeks, or Brussels sprouts.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Belgian Chocolate', @LoganId, 'Famous Belgian chocolate known for its high quality and variety of flavors.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Witloof Gratin', @LoganId, 'Belgian dish of baked endives wrapped in ham and covered with cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Vol-au-Vent', @LoganId, 'Classic Belgian dish of puff pastry filled with a creamy chicken and mushroom sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Flemish Beef Stew', @LoganId, 'Hearty Belgian stew made with beef, beer, and onions.');

INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Croissant', @JulianaId, 'Buttery and flaky French pastry.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Coq au Vin', @JulianaId, 'Classic French chicken dish cooked in red wine with mushrooms and onions.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Ratatouille', @JulianaId, 'Traditional French vegetable stew made with eggplant, zucchini, bell peppers, and tomatoes.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Crème Brûlée', @JulianaId, 'Creamy and caramelized French dessert with a rich custard base.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Quiche Lorraine', @JulianaId, 'Savory French tart filled with bacon, cheese, and custard.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Ajiaco', @JulianaId, 'Traditional Colombian chicken and potato soup with corn and avocado.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Bandeja Paisa', @JulianaId, 'Hearty Colombian platter with rice, beans, beef, pork, chorizo, plantains, avocado, and fried egg.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Sancocho', @JulianaId, 'Hearty Colombian soup with meat, plantains, yuca, corn, and potatoes.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Empanadas', @JulianaId, 'Fried or baked Colombian pastries filled with meat, cheese, or vegetables.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arepa', @JulianaId, 'Traditional Colombian cornmeal cake served with various toppings.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Patacones', @JulianaId, 'Colombian fried plantains served as a side dish or snack.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Bocadillo', @JulianaId, 'Colombian guava paste used as a filling for pastries or eaten with cheese.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Lechona', @JulianaId, 'Colombian roasted pork dish stuffed with rice, peas, and spices.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandebono', @JulianaId, 'Colombian cheese bread made with cornmeal and cheese.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arepas de Choclo', @JulianaId, 'Colombian sweet corn arepas served with cheese and butter.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cazuela de Mariscos', @JulianaId, 'Colombian seafood casserole with fish, shrimp, clams, and mussels.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pescado Frito', @JulianaId, 'Colombian fried fish served with rice, salad, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Sobrebarriga', @JulianaId, 'Colombian flank steak stewed in a tomato-based sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Changua', @JulianaId, 'Colombian milk and egg soup with scallions and bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Arroz con Coco', @JulianaId, 'Colombian coconut rice served with fish or meat.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Pandeyuca', @JulianaId, 'Colombian yuca and cheese bread.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Frijoles Antioqueños', @JulianaId, 'Colombian beans cooked with pork, chorizo, and plantains.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Chicharrón', @JulianaId, 'Colombian crispy pork belly.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Cocadas', @JulianaId, 'Colombian coconut candies.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Papas Chorreadas', @JulianaId, 'Colombian potatoes in a creamy cheese sauce.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Tamales Tolimenses', @JulianaId, 'Colombian tamales filled with pork, chicken, vegetables, and rice.');
INSERT INTO [Recipe] ([Name], [OwnerId], [Description]) VALUES ('Hormigas Culonas', @JulianaId, 'Traditional Colombian dish made with roasted giant ants.');
