CREATE TABLE [dbo].[Recipe]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL,
    [Owner] BIGINT NOT NULL,
    CONSTRAINT [FK_Recipe_To_User] FOREIGN KEY ([Owner]) REFERENCES [User]([Id])
)
