CREATE TABLE [dbo].[Recipe]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL,
    [OwnerId] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Recipe_To_User] FOREIGN KEY ([OwnerId]) REFERENCES [User]([Id])
)
