POST {{HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "FirstName": "John",
  "LastName": "Doe"
}

###

GET {{HostAddress}}/user/details
Authorization: Bearer {{Token}}

###

GET {{HostAddress}}/user/photo
Authorization: Bearer {{Token}}