name: Build and deploy Recipes.Web

env:
  AZURE_STATIC_WEBAPP_NAME: lfarci-test-static
  DOTNET_VERSION: '8.0.x'
  RECIPES_APP_CSPROJ: 'src/Recipes.Web/Recipes.Web.csproj'

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build -c Release ${{ env.RECIPES_APP_CSPROJ }}

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp ${{ env.RECIPES_APP_CSPROJ }}

      - name: Move Azure Static Webapp configuration
        run: mv 'src/Recipes.Web/staticwebapp.config.json' ${{env.DOTNET_ROOT}}/myapp/wwwroot

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: blazor-wasm-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-static-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        id: download-blazor-wasm-app
        uses: actions/download-artifact@v4
        with:
          name: blazor-wasm-app

      - name: Deploy to Azure Static Web App
        id: deploy-to-static-webapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_DUNE_07BFCEA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "wwwroot"
          output_location: ""
          skip_app_build: true
          skip_api_build: true
