name: Deploy Azure resources

env:
  DEPLOYMENT_SCRIPT_IDENTITY: 'app-registration-mi'
  TEMPLATES_DIRECTORY: './infra'
  LOCATION: 'westeurope'
  SCRIPTS_DIRECTORY: './infra/scripts'
  AZURE_CLI_VERSION: '2.63.0' # Keep this version as long as there is no update on https://github.com/Azure/cli/issues/165

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment tag used to build the resource group name'
        required: false
        default: 'Development'
        type: choice
        options:
          - 'Test'
          - 'Production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set resource group name
        run: |
            environment=${{ github.event.inputs.environment || 'Development' }}
            case $environment in
              'Development')
                tag='dev'
                ;;
              'Test')
                tag='tst'
                ;;
              'Production')
                tag='prd'
                ;;
              *)
                tag='dev'
                ;;
            esac
            echo "ENVIRONMENT_TAG=$tag" >> $GITHUB_ENV
            echo "ENVIRONMENT_NAME=$environment" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=lfarci-recipes-${{ github.event.inputs.environment || 'dev' }}-rg" >> $GITHUB_ENV

      - name: Create ${{ env.RESOURCE_GROUP }} resource group
        uses: azure/cli@v2
        with:
          azcliversion: ${{ env.AZURE_CLI_VERSION }}
          inlineScript: |
            az group create \
              --name ${{ env.RESOURCE_GROUP }} \
              --location ${{ env.LOCATION }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create managed identity for the deployment script
        uses: azure/cli@v2
        with:
          azcliversion: ${{ env.AZURE_CLI_VERSION }}
          inlineScript: |
            chmod +x ${{ env.SCRIPTS_DIRECTORY }}/create-script-identity.sh
            ${{ env.SCRIPTS_DIRECTORY }}/create-script-identity.sh \
              --managed-identity-name ${{ env.DEPLOYMENT_SCRIPT_IDENTITY }} \
              --resource-group-name ${{ env.RESOURCE_GROUP }} \
              --tenant-id ${{ secrets.AZURE_TENANT_ID }} \
              --location ${{ env.LOCATION }}

      - id: deploy_azure_resources
        name: Deploy Azure resources to ${{ env.RESOURCE_GROUP }} resource group
        uses: azure/cli@v2
        with:
          azcliversion: ${{ env.AZURE_CLI_VERSION }}
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --template-file "${{ env.TEMPLATES_DIRECTORY }}/main.bicep" \
              --parameters "${{ env.TEMPLATES_DIRECTORY }}/dev.bicepparam" \
              --parameters environmentName=${{ env.ENVIRONMENT_TAG }} \
              --query "{outputs: properties.outputs}" > deployment_output.json

      - name: Authenticate to GitHub CLI
        run: echo ${{ secrets.VARIABLES_PAT }} | gh auth login --with-token

      - name: Set deployment output in the repository secrets
        run: |
          outputs=$(jq -r ".outputs" deployment_output.json)

          gh variable set KEY_VAULT_NAME -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.keyVaultName.value')
          gh variable set DATABASE_ACCOUNT_NAME -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.datebaseAccountName.value')

          gh variable set API_NAME -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.apiName.value')
          gh variable set API_CLIENT_ID -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.apiClientId.value')
          gh variable set API_URI -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.apiUri.value')

          gh variable set SITE_NAME -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.staticSiteName.value')
          gh variable set SITE_CLIENT_ID -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.siteClientId.value')
          gh variable set SITE_URI -e $ENVIRONMENT_NAME -b $(echo $outputs | jq -r '.siteUri.value')