name: Deploy Azure resources

env:
  RESOURCE_GROUP: 'lfarci-recipes-dev-debug-rg'
  DEPLOYMENT_SCRIPT_IDENTITY: 'app-registration-mi'
  TEMPLATES_DIRECTORY: './infra'
  LOCATION: 'westeurope'

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login with a service principal secret: https://github.com/Azure/login#login-with-a-service-principal-secret
      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ${{ env.RESOURCE_GROUP }} resource group
        run: |
          az group create \
            --name ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }}

      - name: Create managed identity for the deployment script
        run: |
          chmod +x ./infra/scripts/create-script-identity.sh
          ./infra/scripts/create-script-identity.sh \
            --managed-identity-name ${{ env.DEPLOYMENT_SCRIPT_IDENTITY }} \
            --resource-group-name ${{ env.RESOURCE_GROUP }} \
            --tenant-id ${{ vars.AZURE_TENANT_ID }} \
            --location ${{ env.LOCATION }}
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}


      - name: Deploy Azure resources to ${{ env.RESOURCE_GROUP }} resource group
        working-directory: ${{ env.TEMPLATES_DIRECTORY }}
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file main.bicep \
            --parameters dev.bicepparam
            --parameters deploymentScriptIdentityName=${{ env.DEPLOYMENT_SCRIPT_IDENTITY }}
