name: Deploy Azure resources

env:
  RESOURCE_GROUP: 'lfarci-recipes-dev-debug-${{ github.run_id }}-rg'
  TEMPLATES_DIRECTORY: './infra'
  LOCATION: 'westeurope'

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        run: |
          az group create \
            --name ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }}

      - name:
        run: |
          ./infra/scripts/create-script-identity.sh \
            --managed-identity-name "app-registration-mi" \
            --resource-group-name ${{ env.RESOURCE_GROUP }} \
            --tenant-id ${{ vars.AZURE_TENANT_ID }} \
            --location ${{ env.LOCATION }}

      - name: Deploy Azure static web app for frontend
        working-directory: ${{ env.TEMPLATES_DIRECTORY }}
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file main.bicep \
            --parameters dev.bicepparam
